apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: xrchat
resources:
  - xrchat-server.yaml
secretGenerator:
  - name: xrchat-dev-secrets
    env: xrchat-dev-secrets.env
generatorOptions:
  disableNameSuffixHash: true