{{- if .Values.server.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xrengine.server.fullname" . }}
  labels:
    {{- include "xrengine.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "xrengine.server.selectorLabels" . | nindent 4 }}
{{- end -}}
