{{- if .Values.server.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "xrengine.server.fullname" . }}
  labels:
    {{- include "xrengine.server.labels" . | nindent 4 }}
data:
{{- if .Values.server.extraEnv }}
{{ toYaml .Values.server.extraEnv | indent 2 }}
{{- end }}
{{- if .Values.server.config }}
  NODE_CONFIG: '{{ mustToJson .Values.server.config }}'
{{- end }}
{{- end -}}
