{{- if .Values.spoke.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "xrengine.spoke.fullname" . }}
  labels:
    {{- include "xrengine.spoke.labels" . | nindent 4 }}
data:
{{- if .Values.spoke.extraEnv }}
{{ toYaml .Values.spoke.extraEnv | indent 2 }}
{{- end }}
{{- if .Values.spoke.config }}
  NODE_CONFIG: '{{ mustToJson .Values.spoke.config }}'
{{- end }}
{{- end }}